server:
  port: 8002
  
# configs for /actuator/info endpoint
info:
  app: 
    name: "${spring.application.name}"
    description: "A simple message consumer."
    version: "1.0.0"

spring:
  application:
    name: message-consumer

---
# for local deployment only.
spring.profiles: default

management:
  endpoints:
    web: 
      exposure:
        include: '*'